seed: 42
run_name: "resnet_max_pool_feature_k_dpp"

model:
  feature_extractor:
    name: ResNetFeatureExtractor
    freeze: false  
    
  aggregator:
    name: MaxPoolAggregator
  classifier:
    name: LinearClassifier

  micro_batch_size: 64

samplers:
  train:
    name: FixedFeatureDppSampler
    params:
      random_proj_dim: 128
      method: "k_dpp"
      k: 16

  val:
    name: UseAllSampler
  test:
    name: UseAllSampler
  
loss:
  mil_loss:
    name: BCE
    params:
      reduction: mean

optimizer:
  name: Adam
  params:
    lr: 1.0e-3
    weight_decay: 1.0e-4

data:
  root: "/home/alpaca/Documents/van/wsi_sampling/data/toy_set"
  batch_size: 4           
  num_workers: 8
  split: "train"          

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  log_every_n_steps: 20  

metrics:
  train:
    Accuracy:
        task: "binary"
        threshold: 0.5
  val:
    Accuracy:
        task: "binary"
        threshold: 0.5
  test:
    Accuracy:
        task: "binary"
        threshold: 0.5