seed: 42
run_name: "resnet_max_pool_feature_dpp"

model:
  feature_extractor:
    name: ResNetFeatureExtractor
    freeze: false  
    
  aggregator:
    name: MaxPoolAggregator
  predictor:
    name: LinearPredictor

  micro_batch_size: 64

samplers:
  train:
    name: FixedFeatureDppSampler
    params:
      method: "standard"
      random_proj_dim: 16

  val:
    name: UseAllSampler
  test:
    name: UseAllSampler
  
loss:
  mil_loss:
    name: BCE
    params:
      reduction: mean

optimizer:
  name: Adam
  params:
    lr: 1.0e-3
    weight_decay: 1.0e-4

dataset:
  tiles_parquet: "../data/toy_set_h5/parquet/tiles.parquet"
  labels_parquet: "../data/toy_set_h5/parquet/labels/slide_labels.parquet"
  splits_parquet: "../data/toy_set_h5/parquet/splits/fold1.parquet"
  features_parquet: "../data/toy_set_h5/parquet/features.parquet"
  lowres_parquet: "../data/toy_set_h5/parquet/lowres/thumbnails.parquet"

dataloader:
  batch_size: 4           
  num_workers: 8

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  logger: true
  enable_checkpointing: false
  enable_model_summary: false
  num_sanity_val_steps: 0


metrics:
  train:
    Accuracy:
        task: "binary"
        threshold: 0.5
  val:
    Accuracy:
        task: "binary"
        threshold: 0.5
  test:
    Accuracy:
        task: "binary"
        threshold: 0.5