seed: 42
run_name: "lusc-luad_attn_mean_pool_frozen_baseline_25"
mode: "frozen_feature"  
model:
  aggregator:
    name: AttnMeanPoolAggregator
    params:
      in_dim: 1024

  predictor:
    name: LinearPredictor
    params:
      in_dim: 1024

optimizer:
  name: Adam
  params:
    lr: 1.0e-3
    weight_decay: 1.0e-4
    
loss:
  mil_loss:
    name: BCE
    params:
      reduction: mean

dataset:
  tiles_parquet: "../data/tcga_luad_lusc/parquet/tiles.parquet"
  labels_parquet: "../data/tcga_luad_lusc/parquet/slide_labels.parquet"
  splits_parquet: "../data/tcga_luad_lusc/parquet/split_1_25train.parquet"
  features_parquet: "../data/tcga_luad_lusc/parquet/features.parquet"

dataloader:
  batch_size: 64           
  num_workers: 32

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  logger: true
  enable_checkpointing: true
  enable_model_summary: false
  num_sanity_val_steps: 0


metrics:
  train:
    Accuracy:
        task: "binary"
        threshold: 0.5
  val:
    Accuracy:
        task: "binary"
        threshold: 0.5
  test:
    Accuracy:
        task: "binary"
        threshold: 0.5

checkpointer:
  save_last: true
  save_top_k: 0
  save_weights_only: true