seed: 42
run_name: "lusc-luad_attn_mean_pool_uniform_25"

checkpoint: /home/dog/Documents/van/wsi_samp/experiments/lusc-luad_attn_mean_pool_frozen_baseline_25/checkpoints/epoch=99-step=300.ckpt

model:
  feature_extractor:
    name: CLAMResNet
    params:
      pretrained: true
      fine_tune_stage: true

  aggregator:
    name: AttnMeanPoolAggregator
    params:
      in_dim: 1024

  predictor:
    name: LinearPredictor
    params:
      in_dim: 1024

  micro_batch_size: 64

optimizer:
  name: Adam
  params:
    lr: 1.0e-5
    weight_decay: 1.0e-4
    
loss:
  mil_loss:
    name: BCE
    params:
      reduction: mean

samplers:
  train:
    name: UniformSampler
    params:
      sample_size: 512
      with_replacement: false

  val:
    name: UseAllSampler
  test:
    name: UseAllSampler

dataset:
  tiles_parquet: "../data/tcga_luad_lusc/parquet/tiles.parquet"
  labels_parquet: "../data/tcga_luad_lusc/parquet/slide_labels.parquet"
  splits_parquet: "../data/tcga_luad_lusc/parquet/split_1_25train.parquet"
  features_parquet: "../data/tcga_luad_lusc/parquet/features.parquet"

dataloader:
  batch_size: 1
  num_workers: 16

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  # strategy: "ddp"
  logger: true
  enable_checkpointing: true
  enable_model_summary: false
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 20
  gradient_clip_val: 1.0
  


metrics:
  train:
    Accuracy:
        task: "binary"
        threshold: 0.5
  val:
    Accuracy:
        task: "binary"
        threshold: 0.5
  test:
    Accuracy:
        task: "binary"
        threshold: 0.5

checkpointer:
  save_last: true
  save_top_k: 0
  save_weights_only: true