seed: 42
run_name: "tcga_lusc-luad_frozen_feature"

mode: "frozen_feature"  
profiler: "pytorch" 

model:
  aggregator:
    name: MeanPoolAggregator
    params:
      in_dim: 1024 

  predictor:
    name: LinearPredictor
    params:
      in_dim: 1024

  micro_batch_size: 64
  
loss:
  mil_loss:
    name: BCE
    params:
      reduction: mean

optimizer:
  name: Adam
  params:
    lr: 1.0e-3
    weight_decay: 1.0e-4


dataset:
  tiles_parquet: "../data/tcga_luad_lusc/parquet/tiles.parquet"
  labels_parquet: "../data/tcga_luad_lusc/parquet/slide_labels.parquet"
  splits_parquet: "../data/tcga_luad_lusc/parquet/split_patient_strat_70_15_15.parquet"
  features_parquet: "../data/tcga_luad_lusc/parquet/features.parquet"

dataloader:
  batch_size: 8
  num_workers: 8

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  logger: true
  enable_checkpointing: false
  enable_model_summary: false
  num_sanity_val_steps: 0


metrics:
  train:
    Accuracy:
        task: "binary"
        threshold: 0.5
  val:
    Accuracy:
        task: "binary"
        threshold: 0.5
  test:
    Accuracy:
        task: "binary"
        threshold: 0.5